/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code.formatter.spotless.app;

class MessageUtils {
	public static String getMessage() {
		return "Hello      World!";
	}
}
